# Teste de requisição POST
GET  http://localhost:3000/api/v1/users
content-type: application/json

###
POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "username": "Bret"
}

###
POST http://localhost:5000/translate
content-type: application/json

{
    "q": "good morning",
    "source": "en",
    "target": "ca",
    "format": "text",
    "api_key": ""

}

###
### MyMemory Translation - GET
GET https://api.mymemory.translated.net/get?q=corrupti inventore&langpair=en|pt
Content-Type: application/json


### Google Translate Free
GET https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=pt&dt=t&q=good morning

###
POST http://localhost:3000/api/v1/keywords
content-type: application/json

{
    "word": "Facilis"
}

###
GET http://localhost:3000/api/v1/keywords
content-type: application/json
